### ISSUE TITLE
localhost:8000/api/schema/reduc-ui gives error ``404``

### ISSUE THREAD

**Issue by Monstarrrr** [Monstarrrr/rebutify#166]

**Comment by seporterfield** [comment]
I couldn't reproduce this on a fresh install.

Make sure all python dependencies are installed
`pip install -r requirements.txt`

And that the database you're testing this with has the necessary migrations
`python manage.py migrate`

**Comment by seporterfield** [comment]
Reproduced the issue

going to 
`localhost:8000/api/schema/reduc-ui` gives a 404
whereas
`localhost:8000/api/schema/reduc-ui/` works fine

This is because we don't normalize URLs by [appending slashes](https://github.com/Monstarrrr/rebutify/blob/b9985bd467893f26ad7b59ebcc2ad1cdafa542f0/backend/rebutify/settings.py#L84) when a URL is entered.

https://github.com/Monstarrrr/rebutify/issues/88 would fix this issue if you don't want to manually add the ending /
